development: null
database: "root:@tcp(localhost:3306)/stayway_test?charset=utf8&parseTime=True&loc=Local&clientFoundRows=true"
logger:
  json: false
  level: info
stayway:
  metasearch:
    base_url: https://stg.stayway.jp
  media:
    base_url: https://stg.stayway.jp/tourism
    files_url: https://stg-files.stayway.jp
aws:
  region: ap-northeast-1
  endpoint: http://minio:9000
  files_bucket: hoge
  upload_expire: 15m
  user_pool_id: dummy
  client_id: dummy
  from_email: noreply@stayway.jp
  persist_media_queue: dummy
wordpress:
  base_url: "https://stg-admin.stayway.jp/tourism"
  basic_auth:
    username: wpuser
    password: wppass
  api_auth:
    username: wpapiuser
    password: wpapipass
  callback_key: wpcallback
google_analytics:
  view_id: 10
slack:
  token: changeme
  callback_key: changeme
  report_channel: changeme
payjp:
  secret_key: changeme
cf_project:
  system_fee: 220

# vim: set ft=yaml:
