development: null
database: "root:@tcp(localhost:3306)/stayway_test?charset=utf8&parseTime=True&loc=Local&clientFoundRows=true"
logger:
  json: false
  level: info
stayway:
  metasearch:
    base_url: http://host.docker.internal:3000
  media:
    base_url: http://localhost:5000/tourism
    files_url: TBD
aws:
  region: ap-northeast-1
  endpoint: http://localstack:4572
  files_bucket: hoge
  upload_expire: 15m
wordpress:
  base_url: https://stg.stayway.jp/tourism
  user: changeme
  password: changeme
  callback_key: hoge
slack:
  token: changeme
  callback_key: changeme
  report_channel: changeme

# vim: set ft=yaml:
